import { StyleSheet } from 'react-native';
import { MEMBER_PANEL_HANDLE_HEIGHT, MEMBER_PANEL_HEIGHT } from './MapDashboard.helpers';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F7FA' },
  noTripContainer: { backgroundColor: '#FFFFFF' },
  sosBanner: { backgroundColor: '#D9534F', padding: 12, alignItems: 'center' },
  sosText: { color: 'white', fontWeight: 'bold', fontSize: 15 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 4,
    paddingBottom: 8,
    backgroundColor: 'white',
  },
  tripName: { fontSize: 18, fontWeight: 'bold', color: '#1A1A2E' },
  memberCount: { fontSize: 13, color: '#666', marginTop: 2 },
  modeText: { fontSize: 12, color: '#007AFF', marginTop: 2, fontWeight: '600' },
  settingsIcon: { fontSize: 24 },
  codeButton: {
    backgroundColor: '#007AFF',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  codeButtonText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 14,
  },
  mapCard: {
    flex: 1,
    marginHorizontal: 16,
    marginTop: 0,
    marginBottom: 8,
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#DDE1E6',
    backgroundColor: '#FFFFFF',
  },
  mapFullScreen: {
    flex: 1,
    marginHorizontal: 16,
    marginTop: 0,
    marginBottom: 0,
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#DDE1E6',
    backgroundColor: '#FFFFFF',
  },
  map: { flex: 1, width: '100%' },
  fullMap: { flex: 1, width: '100%' },
  mapControls: {
    position: 'absolute',
    top: 0,
    left: 20,
    right: 20,
  },
  meetingAlertBanner: {
    backgroundColor: '#FFF4BF',
    borderColor: '#F6C80A',
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 8,
  },
  meetingAlertTitle: {
    color: '#7A5A00',
    fontSize: 13,
    fontWeight: '700',
  },
  meetingAlertSubtitle: {
    color: '#9C7400',
    fontSize: 12,
    marginTop: 2,
  },
  searchBox: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 6,
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchInput: { flex: 1, fontSize: 14, color: '#000000', paddingHorizontal: 10, paddingVertical: 8 },
  searchButton: { backgroundColor: '#007AFF', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10 },
  searchButtonDisabled: { backgroundColor: '#8FBFFF' },
  searchButtonText: { color: 'white', fontWeight: '600', fontSize: 13 },
  mapTypeButton: {
    marginTop: 10,
    alignSelf: 'flex-end',
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  mapTypeButtonText: { color: '#1A1A2E', fontWeight: '600', fontSize: 12 },
  suggestionList: {
    marginTop: 0,
    backgroundColor: 'white',
    borderRadius: 12,
    overflow: 'hidden',
  },
  suggestionLoadingRow: {
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  suggestionItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: '#F1F3F6',
  },
  suggestionTitle: { color: '#1A1A2E', fontWeight: '600', fontSize: 13 },
  suggestionSubtitle: { color: '#666', fontSize: 12, marginTop: 2 },
  locateButton: {
    marginTop: 0,
    alignSelf: 'flex-end',
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchIconButton: {
    backgroundColor: '#007AFF',
    borderRadius: 20,
    width: 40,
    height: 40,
    marginTop: 10,
    alignSelf: 'flex-end',
    justifyContent: 'center',
    alignItems: 'center',
  },
  locateButtonDisabled: { opacity: 0.6 },
  locateButtonIcon: { color: '#1A1A2E', fontWeight: '700', fontSize: 20, lineHeight: 20 },
  errorText: { color: '#D9534F', marginTop: 8, marginHorizontal: 20 },
  memberPanel: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 0,
    height: MEMBER_PANEL_HEIGHT,
    backgroundColor: 'rgba(255,255,255,0.97)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#DDE1E6',
    overflow: 'hidden',
  },
  memberPanelHeader: {
    height: MEMBER_PANEL_HANDLE_HEIGHT,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#EEF1F4',
    position: 'relative',
  },
  memberPanelArrow: { fontSize: 16, color: '#1A1A2E', fontWeight: '700' },
  memberPanelListContent: { paddingHorizontal: 20, paddingTop: 10, paddingBottom: 14 },
  startJourneyButtonContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  startJourneyButton: {
    backgroundColor: '#007AFF',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  startJourneyButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },
  sectionTitle: { fontSize: 14, fontWeight: 'bold', color: '#1A1A2E', marginBottom: 8 },
  memberRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  memberAvatar: { fontSize: 18, marginRight: 8 },
  memberMeta: { flex: 1 },
  memberName: { fontSize: 15, color: '#333' },
  memberMode: { fontSize: 12, color: '#777', marginTop: 2 },
  battery: { fontSize: 14, color: 'green' },
  lowBattery: { fontSize: 14, color: 'red', fontWeight: 'bold' },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: 12,
    paddingBottom: 10,
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  navBtn: { padding: 10, borderRadius: 10, backgroundColor: '#F0F7FF' },
  navBtnText: { color: '#007AFF', fontWeight: '600' },
  sosBtn: { backgroundColor: '#D9534F', padding: 12, borderRadius: 12 },
  sosBtnActive: { backgroundColor: '#888' },
  sosBtnText: { color: 'white', fontWeight: 'bold', fontSize: 15 },
  homeBottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 16,
    paddingBottom: 10,
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  navItem: { alignItems: 'center' },
  navLabel: { fontSize: 13, color: '#666', marginTop: 2 },
  memberSheet: {
    marginHorizontal: 16,
    marginBottom: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#DDE1E6',
    backgroundColor: 'rgba(255,255,255,0.97)',
    overflow: 'hidden',
  },
  memberSheetHeader: {
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#EEF1F4',
  },
  memberSheetTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1A1A2E',
  },
  memberSheetHint: {
    fontSize: 12,
    color: '#667085',
    marginTop: 2,
  },
  memberSheetArrow: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1A2E',
  },
  memberSheetList: {
    maxHeight: 220,
    backgroundColor: '#FFFFFF',
  },
  memberSheetListContent: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 12,
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 24,
    width: '80%',
    maxWidth: 320,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1A1A2E',
  },
  modalCloseButton: {
    padding: 8,
  },
  modalCloseText: {
    fontSize: 24,
    color: '#666',
  },
  modalBody: {
    alignItems: 'center',
    marginBottom: 24,
  },
  codeDisplay: {
    fontSize: 32,
    fontWeight: '800',
    color: '#007AFF',
    letterSpacing: 2,
    marginBottom: 12,
  },
  codeText: {
    fontSize: 13,
    color: '#666',
    textAlign: 'center',
  },
  modalCloseBtn: {
    backgroundColor: '#007AFF',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  modalCloseBtnText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 16,
  },
});
