import { StyleSheet } from 'react-native';
import { MEMBER_PANEL_HANDLE_HEIGHT, MEMBER_PANEL_HEIGHT } from './MapDashboard.helpers';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F7FA' },
  noTripContainer: { backgroundColor: '#FFFFFF' },
  sosBanner: { backgroundColor: '#D9534F', padding: 12, alignItems: 'center' },
  sosText: { color: 'white', fontWeight: 'bold', fontSize: 15 },
  tripCodeBanner: {
    position: 'absolute',
    top: 30,
    alignSelf: 'center',
    zIndex: 20,
    backgroundColor: 'rgba(254, 254, 255, 0.9)',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
  },
  tripCodeLabel: { color: 'black', fontWeight: '700', fontSize: 24, letterSpacing: 0.4 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 8,
    backgroundColor: 'white',
  },
  tripName: { fontSize: 20, fontWeight: 'bold', color: '#1A1A2E' },
  memberCount: { fontSize: 13, color: '#666', marginTop: 2 },
  modeText: { fontSize: 12, color: '#007AFF', marginTop: 2, fontWeight: '600' },
  settingsIcon: { fontSize: 24 },
  mapCard: {
    flex: 1,
    marginHorizontal: 0,
    marginTop: 0,
    borderRadius: 0,
    overflow: 'hidden',
    borderWidth: 0,
  },
  mapFullScreen: { flex: 1 },
  map: { flex: 1, width: '100%' },
  fullMap: { flex: 1, width: '100%' },
  mapControls: {
    position: 'absolute',
    top: 24,
    left: 12,
    right: 12,
  },
  searchBox: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 6,
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchInput: { flex: 1, fontSize: 14, color: '#222', paddingHorizontal: 10, paddingVertical: 8 },
  searchButton: { backgroundColor: '#007AFF', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10 },
  searchButtonDisabled: { backgroundColor: '#8FBFFF' },
  searchButtonText: { color: 'white', fontWeight: '600', fontSize: 13 },
  mapTypeButton: {
    marginTop: 8,
    alignSelf: 'flex-end',
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  mapTypeButtonText: { color: '#1A1A2E', fontWeight: '600', fontSize: 12 },
  suggestionList: {
    marginTop: 6,
    backgroundColor: 'white',
    borderRadius: 12,
    overflow: 'hidden',
  },
  suggestionLoadingRow: {
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  suggestionItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: '#F1F3F6',
  },
  suggestionTitle: { color: '#1A1A2E', fontWeight: '600', fontSize: 13 },
  suggestionSubtitle: { color: '#666', fontSize: 12, marginTop: 2 },
  locateButton: {
    marginTop: 8,
    alignSelf: 'flex-end',
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  locateButtonDisabled: { opacity: 0.6 },
  locateButtonIcon: { color: '#1A1A2E', fontWeight: '700', fontSize: 20, lineHeight: 20 },
  errorText: { color: '#D9534F', marginTop: 8, marginHorizontal: 14 },
  memberPanel: {
    position: 'absolute',
    left: 10,
    right: 10,
    bottom: 8,
    height: MEMBER_PANEL_HEIGHT,
    backgroundColor: 'rgba(255,255,255,0.97)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#DDE1E6',
    overflow: 'hidden',
  },
  memberPanelHeader: {
    height: MEMBER_PANEL_HANDLE_HEIGHT,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#EEF1F4',
    position: 'relative',
  },
  memberPanelArrow: { fontSize: 16, color: '#1A1A2E', fontWeight: '700' },
  memberPanelListContent: { paddingHorizontal: 14, paddingTop: 10, paddingBottom: 14 },
  startJourneyButtonContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  startJourneyButton: {
    backgroundColor: '#007AFF',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  startJourneyButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },
  sectionTitle: { fontSize: 14, fontWeight: 'bold', color: '#1A1A2E', marginBottom: 8 },
  memberRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  memberAvatar: { fontSize: 18, marginRight: 8 },
  memberMeta: { flex: 1 },
  memberName: { fontSize: 15, color: '#333' },
  memberMode: { fontSize: 12, color: '#777', marginTop: 2 },
  battery: { fontSize: 14, color: 'green' },
  lowBattery: { fontSize: 14, color: 'red', fontWeight: 'bold' },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: 12,
    paddingBottom: 24,
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  navBtn: { padding: 10, borderRadius: 10, backgroundColor: '#F0F7FF' },
  navBtnText: { color: '#007AFF', fontWeight: '600' },
  sosBtn: { backgroundColor: '#D9534F', padding: 12, borderRadius: 12 },
  sosBtnActive: { backgroundColor: '#888' },
  sosBtnText: { color: 'white', fontWeight: 'bold', fontSize: 15 },
  homeBottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 16,
    paddingBottom: 36,
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  navItem: { alignItems: 'center' },
  navLabel: { fontSize: 13, color: '#666', marginTop: 2 },
});
