import { StyleSheet } from 'react-native';
import { MEMBER_PANEL_HANDLE_HEIGHT, MEMBER_PANEL_HEIGHT } from './MapDashboard.helpers';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0B1220', paddingTop: 40, paddingBottom: 0 },
  noTripContainer: { backgroundColor: 'rgba(17, 24, 39, 0.9)' },
  sosBanner: { backgroundColor: '#D9534F', padding: 12, alignItems: 'center' },
  sosText: { color: 'white', fontWeight: 'bold', fontSize: 15 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 4,
    paddingBottom: 8,
    backgroundColor: 'rgba(17, 24, 39, 0.9)',
  },
  tripName: { fontSize: 18, fontWeight: 'bold', color: '#F3F4F6' },
  memberCount: { fontSize: 13, color: '#D1D5DB', marginTop: 2 },
  modeText: { fontSize: 12, color: '#007AFF', marginTop: 2, fontWeight: '600' },
  settingsIcon: { fontSize: 24 },
  codeButton: {
    backgroundColor: '#007AFF',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  codeButtonText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 14,
  },
  mapCard: {
    flex: 1,
    marginHorizontal: 16,
    marginTop: 0,
    marginBottom: 0,
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#4B5563',
    backgroundColor: 'rgba(17, 24, 39, 0.88)',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  mapFullScreen: {
    flex: 1,
    marginHorizontal: 16,
    marginTop: 0,
    marginBottom: 0,
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#4B5563',
    backgroundColor: 'rgba(17, 24, 39, 0.88)',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  map: { flex: 1, width: '100%' },
  fullMap: { flex: 1, width: '100%' },
  mapControls: {
    position: 'absolute',
    top: 0,
    left: 20,
    right: 20,
  },
  meetingAlertBanner: {
    backgroundColor: '#FFF4BF',
    borderColor: '#F6C80A',
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 8,
  },
  meetingAlertTitle: {
    color: '#7A5A00',
    fontSize: 13,
    fontWeight: '700',
  },
  meetingAlertSubtitle: {
    color: '#9C7400',
    fontSize: 12,
    marginTop: 2,
  },
  searchBox: {
    backgroundColor: 'rgba(31, 41, 55, 0.94)',
    borderRadius: 14,
    padding: 6,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#4B5563',
  },
  searchInput: { flex: 1, fontSize: 14, color: '#F3F4F6', paddingHorizontal: 10, paddingVertical: 8 },
  searchButton: { backgroundColor: '#007AFF', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10 },
  searchButtonDisabled: { backgroundColor: '#8FBFFF' },
  searchButtonText: { color: 'white', fontWeight: '600', fontSize: 13 },
  mapTypeButton: {
    marginTop: 10,
    alignSelf: 'flex-end',
    backgroundColor: 'rgba(31, 41, 55, 0.95)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  mapTypeButtonText: { color: '#E5E7EB', fontWeight: '600', fontSize: 12 },
  suggestionList: {
    marginTop: 0,
    backgroundColor: 'rgba(31, 41, 55, 0.95)',
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#4B5563',
  },
  suggestionLoadingRow: {
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  suggestionItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: '#4B5563',
  },
  suggestionTitle: { color: '#F3F4F6', fontWeight: '600', fontSize: 13 },
  suggestionSubtitle: { color: '#D1D5DB', fontSize: 12, marginTop: 2 },
  locateButton: {
    marginTop: 0,
    alignSelf: 'flex-end',
    backgroundColor: 'rgba(31, 41, 55, 0.95)',
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchIconButton: {
    backgroundColor: '#007AFF',
    borderRadius: 20,
    width: 40,
    height: 40,
    marginTop: 10,
    alignSelf: 'flex-end',
    justifyContent: 'center',
    alignItems: 'center',
  },
  locateButtonDisabled: { opacity: 0.6 },
  locateButtonIcon: { color: '#E5E7EB', fontWeight: '700', fontSize: 20, lineHeight: 20 },
  errorText: { color: '#D9534F', marginTop: 8, marginHorizontal: 20 },
  memberPanel: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 0,
    height: MEMBER_PANEL_HEIGHT,
    backgroundColor: 'rgba(31, 41, 55, 0.96)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#4B5563',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  memberPanelHeader: {
    height: MEMBER_PANEL_HANDLE_HEIGHT,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#EEF1F4',
    position: 'relative',
  },
  memberPanelArrow: { fontSize: 16, color: '#E5E7EB', fontWeight: '700' },
  memberPanelListContent: { paddingHorizontal: 20, paddingTop: 10, paddingBottom: 14 },
  startJourneyButtonContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  startJourneyButton: {
    backgroundColor: '#007AFF',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  startJourneyButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },
  sectionTitle: { fontSize: 14, fontWeight: 'bold', color: '#F3F4F6', marginBottom: 8 },
  memberRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  memberAvatar: { fontSize: 18, marginRight: 8 },
  memberMeta: { flex: 1 },
  memberName: { fontSize: 15, color: '#F3F4F6' },
  memberMode: { fontSize: 12, color: '#D1D5DB', marginTop: 2 },
  battery: { fontSize: 14, color: 'green' },
  lowBattery: { fontSize: 14, color: 'red', fontWeight: 'bold' },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginHorizontal: 0,
    marginTop: 0,
    marginBottom: 0,
    paddingVertical: 12,
    paddingBottom: 8,
    backgroundColor: 'rgba(17, 24, 39, 0.95)',
    borderTopWidth: 1,
    borderTopColor: '#4B5563',
  },
  navBtn: { paddingVertical: 10, paddingHorizontal: 12, borderRadius: 12, backgroundColor: '#F0F7FF' },
  navBtnText: { color: '#007AFF', fontWeight: '700' },
  sosBtn: { backgroundColor: '#D9534F', paddingVertical: 12, paddingHorizontal: 12, borderRadius: 12 },
  sosBtnActive: { backgroundColor: '#888' },
  sosBtnText: { color: 'white', fontWeight: '700', fontSize: 15 },
  homeBottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 14,
    paddingBottom: 8,
    backgroundColor: 'rgba(17, 24, 39, 0.95)',
    borderTopWidth: 1,
    borderTopColor: '#4B5563',
  },
  navItem: { alignItems: 'center' },
  navLabel: { fontSize: 13, color: '#667085', marginTop: 2 },
  memberSheet: {
    marginHorizontal: 16,
    marginBottom: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#4B5563',
    backgroundColor: 'rgba(31, 41, 55, 0.96)',
    overflow: 'hidden',
  },
  memberSheetHeader: {
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(31, 41, 55, 0.96)',
    borderBottomWidth: 1,
    borderBottomColor: '#4B5563',
  },
  memberSheetTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#F3F4F6',
  },
  memberSheetHint: {
    fontSize: 12,
    color: '#D1D5DB',
    marginTop: 2,
  },
  memberSheetArrow: {
    fontSize: 16,
    fontWeight: '700',
    color: '#E5E7EB',
  },
  memberSheetList: {
    maxHeight: 220,
    backgroundColor: 'rgba(31, 41, 55, 0.96)',
  },
  memberSheetListContent: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 12,
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  modalContent: {
    backgroundColor: 'rgba(31, 41, 55, 0.96)',
    borderRadius: 20,
    padding: 24,
    width: '80%',
    maxWidth: 320,
    elevation: 10,
    borderWidth: 1,
    borderColor: '#4B5563',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#F3F4F6',
  },
  modalCloseButton: {
    padding: 8,
  },
  modalCloseText: {
    fontSize: 24,
    color: '#D1D5DB',
  },
  modalBody: {
    alignItems: 'center',
    marginBottom: 24,
  },
  codeDisplay: {
    fontSize: 32,
    fontWeight: '800',
    color: '#007AFF',
    letterSpacing: 2,
    marginBottom: 12,
  },
  codeText: {
    fontSize: 13,
    color: '#D1D5DB',
    textAlign: 'center',
  },
  modalCloseBtn: {
    backgroundColor: '#007AFF',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  modalCloseBtnText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 16,
  },
});
