import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: 'transparent', paddingTop: 12, paddingBottom: 10 },
  backgroundImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    opacity: 0.08,
  },
  darkScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(2, 6, 23, 0.65)',
  },
  vignette: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
  },
  ambient: {
    position: 'absolute',
    borderRadius: 999,
    opacity: 0.22,
  },
  ambientOne: {
    width: 220,
    height: 220,
    top: 54,
    right: -70,
    backgroundColor: '#C9D9FF',
  },
  ambientTwo: {
    width: 180,
    height: 180,
    bottom: 120,
    left: -55,
    backgroundColor: '#FFE1D9',
  },
  heroPanel: {
    flex: 1,
    marginHorizontal: 14,
    marginTop: 26,
    marginBottom: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(75, 85, 99, 0.75)',
    backgroundColor: 'rgba(17, 24, 39, 0.84)',
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
    zIndex: 1,
  },
  header: { alignItems: 'center', paddingTop: 28, paddingBottom: 12, zIndex: 1 },
  logo: {
    fontSize: 30,
    fontWeight: '800',
    color: '#F3F4F6',
  },
  subtitle: {
    fontSize: 14,
    color: '#D1D5DB',
    marginTop: 5,
  },
  illustrationContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', zIndex: 1 },
  illustrationImage: { width: 300, height: 190, marginHorizontal: 20, opacity: 0.98 },
  buttonContainer: { paddingHorizontal: 20, paddingBottom: 24, zIndex: 1 },
  primaryButton: {
    backgroundColor: '#007AFF',
    paddingVertical: 15,
    borderRadius: 14,
    alignItems: 'center',
    marginBottom: 12,
  },
  primaryButtonText: { color: 'white', fontSize: 16, fontWeight: '700' },
  secondaryButton: {
    backgroundColor: 'rgba(31, 41, 55, 0.9)',
    paddingVertical: 15,
    borderRadius: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#4B5563',
  },
  secondaryButtonText: { color: '#E5E7EB', fontSize: 16, fontWeight: '700' },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 16,
    paddingBottom: 14,
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderTopColor: '#DDE1E6',
  },
  navItem: { alignItems: 'center' },
  navLabel: { fontSize: 13, color: '#667085', marginTop: 2 },
});
