import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#050b18' },
  backgroundImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  darkScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(5, 12, 24, 0.62)',
  },
  vignette: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(2, 9, 20, 0.42)',
  },
  ambient: {
    position: 'absolute',
    borderRadius: 999,
    opacity: 0.18,
  },
  ambientOne: {
    width: 260,
    height: 260,
    top: 70,
    right: -90,
    backgroundColor: '#1ea7a1',
  },
  ambientTwo: {
    width: 220,
    height: 220,
    bottom: 110,
    left: -80,
    backgroundColor: '#ff5f45',
  },
  heroPanel: {
    flex: 1,
    marginHorizontal: 14,
    marginTop: 18,
    marginBottom: 10,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(194, 211, 255, 0.2)',
    backgroundColor: 'rgba(14, 23, 40, 0.66)',
    zIndex: 1,
  },
  header: { alignItems: 'center', paddingTop: 24, paddingBottom: 8, zIndex: 1 },
  logo: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0,0,0,0.9)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 8,
  },
  subtitle: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.88)',
    marginTop: 5,
    textShadowColor: 'rgba(0,0,0,0.9)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 7,
  },
  illustrationContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', zIndex: 1 },
  illustrationImage: { width: 300, height: 190, marginHorizontal: 20 },
  buttonContainer: { paddingHorizontal: 32, paddingBottom: 20, zIndex: 1 },
  primaryButton: {
    backgroundColor: '#ff5f45',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 12,
  },
  primaryButtonText: { color: 'white', fontSize: 16, fontWeight: 'bold' },
  secondaryButton: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1.2,
    borderColor: 'rgba(194, 211, 255, 0.28)',
  },
  secondaryButtonText: { color: '#E7EEFC', fontSize: 16, fontWeight: 'bold' },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 16,
    paddingBottom: 50,
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  navItem: { alignItems: 'center' },
  navLabel: { fontSize: 13, color: '#666', marginTop: 2 },
});
