import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#050b18',
    paddingTop: 8,
    paddingBottom: 8,
  },
  backgroundImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  darkScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(5, 12, 24, 0.62)',
  },
  vignette: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(2, 9, 20, 0.42)',
  },
  ambient: {
    position: 'absolute',
    borderRadius: 999,
    opacity: 0.18,
  },
  ambientOne: {
    width: 260,
    height: 260,
    top: 80,
    right: -90,
    backgroundColor: '#1ea7a1',
  },
  ambientTwo: {
    width: 220,
    height: 220,
    bottom: 100,
    left: -80,
    backgroundColor: '#ff5f45',
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    justifyContent: 'center',
    zIndex: 1,
    marginHorizontal: 14,
    marginVertical: 24,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(75, 85, 99, 0.7)',
    backgroundColor: 'rgba(17, 24, 39, 0.82)',
  },
  logo: {
    fontSize: 34,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 12,
    textShadowColor: 'rgba(0,0,0,0.9)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 8,
  },
  subtitle: {
    fontSize: 15,
    color: 'rgba(255,255,255,0.88)',
    textAlign: 'center',
    marginBottom: 36,
    textShadowColor: 'rgba(0,0,0,0.9)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 7,
  },
  primaryButton: {
    backgroundColor: '#0891B2',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 12,
  },
  primaryButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },
  secondaryButton: {
    backgroundColor: 'rgba(31, 41, 55, 0.85)',
    borderWidth: 1.2,
    borderColor: 'rgba(107, 114, 128, 0.7)',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  secondaryButtonText: {
    color: '#E7EEFC',
    fontSize: 16,
    fontWeight: '700',
  },
});
