import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    maxWidth: 460,
    alignSelf: 'center',
    backgroundColor: 'rgba(11, 18, 32, 0.92)',
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 14,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: '#3F4A5E',
    shadowColor: '#020617',
    shadowOpacity: 0.24,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  headerCard: {
    backgroundColor: 'rgba(31, 41, 55, 0.94)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#4B5563',
    paddingHorizontal: 14,
    paddingVertical: 13,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  title: { fontSize: 24, fontWeight: '800', color: '#F3F4F6', marginBottom: 4 },
  subtitle: { fontSize: 13, color: '#D1D5DB', marginBottom: 12, lineHeight: 18 },
  ownerOnlyText: {
    fontSize: 12,
    color: '#B45309',
    backgroundColor: '#FFEDD5',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
  },
  hintText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#7A5A00',
    backgroundColor: '#FFF6CC',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  mapCard: {
    flex: 1,
    backgroundColor: 'rgba(17, 24, 39, 0.95)',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#4B5563',
    overflow: 'hidden',
    marginBottom: 14,
    minHeight: 320,
  },
  map: { flex: 1, width: '100%' },
  mapInfoPill: {
    position: 'absolute',
    top: 12,
    left: 12,
    right: 12,
    backgroundColor: 'rgba(15, 23, 42, 0.82)',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#475569',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  mapInfoText: { color: '#E2E8F0', fontSize: 12, fontWeight: '600', textAlign: 'center' },
  actionsRow: { gap: 10, paddingBottom: 2 },
  saveBtn: {
    backgroundColor: '#007AFF',
    paddingVertical: 15,
    borderRadius: 14,
    alignItems: 'center',
    shadowColor: '#0B4FA9',
    shadowOpacity: 0.28,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  saveBtnText: { color: 'white', fontSize: 16, fontWeight: '700' },
  cancelBtn: {
    backgroundColor: '#D9534F',
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
  },
  cancelBtnText: { color: 'white', fontSize: 15, fontWeight: '700' },
});
