import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0B1220', paddingHorizontal: 16, paddingTop: 20, paddingBottom: 14 },
  headerCard: {
    backgroundColor: 'rgba(31, 41, 55, 0.9)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#4B5563',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  title: { fontSize: 24, fontWeight: '800', color: '#F3F4F6', marginBottom: 6 },
  subtitle: { fontSize: 14, color: '#D1D5DB', marginBottom: 16 },
  ownerOnlyText: {
    fontSize: 12,
    color: '#B45309',
    backgroundColor: '#FFEDD5',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    marginBottom: 8,
  },
  hintText: {
    fontSize: 13,
    color: '#7A5A00',
    backgroundColor: '#FFF6CC',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  mapCard: {
    flex: 1,
    backgroundColor: 'rgba(17, 24, 39, 0.88)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#4B5563',
    overflow: 'hidden',
    marginBottom: 16,
  },
  map: { flex: 1, width: '100%' },
  mapPlaceholder: { flex: 1, backgroundColor: '#D4E8C2', borderRadius: 16, justifyContent: 'center', alignItems: 'center', marginBottom: 16 },
  mapText: { fontSize: 18, color: '#555', position: 'absolute', top: 16 },
  pinContainer: { alignItems: 'center' },
  pin: { fontSize: 40 },
  pinLabel: { backgroundColor: 'white', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8, fontWeight: '600', marginTop: 4 },
  actionsRow: { gap: 10 },
  saveBtn: { backgroundColor: '#007AFF', paddingVertical: 15, borderRadius: 14, alignItems: 'center' },
  saveBtnText: { color: 'white', fontSize: 16, fontWeight: '700' },
  cancelBtn: { backgroundColor: '#D9534F', paddingVertical: 14, borderRadius: 14, alignItems: 'center' },
  cancelBtnText: { color: 'white', fontSize: 15, fontWeight: '700' },
});
