import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F7FA', padding: 16 },
  headerCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
  },
  title: { fontSize: 22, fontWeight: 'bold', color: '#1A1A2E', marginBottom: 6 },
  subtitle: { fontSize: 14, color: '#666', marginBottom: 16 },
  ownerOnlyText: {
    fontSize: 12,
    color: '#B45309',
    backgroundColor: '#FFEDD5',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    marginBottom: 8,
  },
  hintText: {
    fontSize: 13,
    color: '#7A5A00',
    backgroundColor: '#FFF6CC',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  mapCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#DDE1E6',
    overflow: 'hidden',
    marginBottom: 16,
  },
  mapPlaceholder: { flex: 1, backgroundColor: '#D4E8C2', borderRadius: 16, justifyContent: 'center', alignItems: 'center', marginBottom: 16 },
  mapText: { fontSize: 18, color: '#555', position: 'absolute', top: 16 },
  pinContainer: { alignItems: 'center' },
  pin: { fontSize: 40 },
  pinLabel: { backgroundColor: 'white', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8, fontWeight: '600', marginTop: 4 },
  actionsRow: { gap: 10 },
  saveBtn: { backgroundColor: '#2ECC71', padding: 16, borderRadius: 12, alignItems: 'center' },
  saveBtnText: { color: 'white', fontSize: 16, fontWeight: 'bold' },
  cancelBtn: { backgroundColor: '#D9534F', padding: 14, borderRadius: 12, alignItems: 'center' },
  cancelBtnText: { color: 'white', fontSize: 15, fontWeight: '700' },
});
