import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F7FA', padding: 16 },
  heading: { fontSize: 24, fontWeight: 'bold', marginBottom: 12, color: '#1A1A2E' },
  input: {
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#DDE1E6',
    borderRadius: 10,
    padding: 12,
    fontSize: 15,
    marginBottom: 12,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  searchInput: {
    flex: 1,
    marginBottom: 0,
  },
  searchBtn: {
    backgroundColor: '#007AFF',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  searchBtnText: {
    color: 'white',
    fontWeight: '700',
  },
  suggestionList: {
    marginTop: 8,
    backgroundColor: 'white',
    borderRadius: 12,
    overflow: 'hidden',
  },
  suggestionLoadingRow: {
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  suggestionItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: '#F1F3F6',
  },
  suggestionTitle: {
    color: '#1A1A2E',
    fontWeight: '600',
    fontSize: 13,
  },
  suggestionSubtitle: {
    color: '#666',
    fontSize: 12,
    marginTop: 2,
  },
  mapCard: {
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#DDE1E6',
    marginTop: 12,
    position: 'relative',
  },
  map: {
    height: 280,
    width: '100%',
  },
  expandedMapContainer: {
    flex: 1,
    backgroundColor: '#F5F7FA',
  },
  expandedMap: {
    flex: 1,
    width: '100%',
  },
  expandHintContainer: {
    position: 'absolute',
    left: 10,
    bottom: 10,
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  expandHintText: {
    color: '#1A1A2E',
    fontSize: 12,
    fontWeight: '600',
  },
  locateButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  locateButtonDisabled: { opacity: 0.6 },
  locateButtonIcon: {
    color: '#1A1A2E',
    fontWeight: '700',
    fontSize: 20,
    lineHeight: 20,
  },
  closeExpandedMapButton: {
    position: 'absolute',
    right: 10,
    bottom: 18,
    backgroundColor: '#007AFF',
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  closeExpandedMapButtonText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 13,
  },
  destinationText: {
    marginTop: 10,
    color: '#333',
    fontSize: 13,
    minHeight: 36,
  },
  createButton: {
    backgroundColor: '#007AFF',
    borderRadius: 12,
    alignItems: 'center',
    paddingVertical: 14,
    marginTop: 6,
  },
  createButtonDisabled: {
    opacity: 0.7,
  },
  createButtonText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 16,
  },
  codeText: {
    marginTop: 12,
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1A2E',
    letterSpacing: 1,
  },
});
